/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RSplatRouteImport } from './routes/r.$'
import { Route as WorkspaceFileIdPageIdRouteImport } from './routes/workspace/$fileId.$pageId'
import { Route as TokensFileIdPageIdRouteImport } from './routes/tokens/$fileId.$pageId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSplatRoute = RSplatRouteImport.update({
  id: '/r/$',
  path: '/r/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceFileIdPageIdRoute = WorkspaceFileIdPageIdRouteImport.update({
  id: '/workspace/$fileId/$pageId',
  path: '/workspace/$fileId/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensFileIdPageIdRoute = TokensFileIdPageIdRouteImport.update({
  id: '/tokens/$fileId/$pageId',
  path: '/tokens/$fileId/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/r/$': typeof RSplatRoute
  '/tokens/$fileId/$pageId': typeof TokensFileIdPageIdRoute
  '/workspace/$fileId/$pageId': typeof WorkspaceFileIdPageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/r/$': typeof RSplatRoute
  '/tokens/$fileId/$pageId': typeof TokensFileIdPageIdRoute
  '/workspace/$fileId/$pageId': typeof WorkspaceFileIdPageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/r/$': typeof RSplatRoute
  '/tokens/$fileId/$pageId': typeof TokensFileIdPageIdRoute
  '/workspace/$fileId/$pageId': typeof WorkspaceFileIdPageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/r/$'
    | '/tokens/$fileId/$pageId'
    | '/workspace/$fileId/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/r/$'
    | '/tokens/$fileId/$pageId'
    | '/workspace/$fileId/$pageId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/r/$'
    | '/tokens/$fileId/$pageId'
    | '/workspace/$fileId/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RSplatRoute: typeof RSplatRoute
  TokensFileIdPageIdRoute: typeof TokensFileIdPageIdRoute
  WorkspaceFileIdPageIdRoute: typeof WorkspaceFileIdPageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$': {
      id: '/r/$'
      path: '/r/$'
      fullPath: '/r/$'
      preLoaderRoute: typeof RSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$fileId/$pageId': {
      id: '/workspace/$fileId/$pageId'
      path: '/workspace/$fileId/$pageId'
      fullPath: '/workspace/$fileId/$pageId'
      preLoaderRoute: typeof WorkspaceFileIdPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/$fileId/$pageId': {
      id: '/tokens/$fileId/$pageId'
      path: '/tokens/$fileId/$pageId'
      fullPath: '/tokens/$fileId/$pageId'
      preLoaderRoute: typeof TokensFileIdPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RSplatRoute: RSplatRoute,
  TokensFileIdPageIdRoute: TokensFileIdPageIdRoute,
  WorkspaceFileIdPageIdRoute: WorkspaceFileIdPageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
