/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceFileIdRouteImport } from './routes/workspace/$fileId'
import { Route as WorkspaceFileIdPageIdRouteImport } from './routes/workspace/$fileId.$pageId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceFileIdRoute = WorkspaceFileIdRouteImport.update({
  id: '/workspace/$fileId',
  path: '/workspace/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceFileIdPageIdRoute = WorkspaceFileIdPageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => WorkspaceFileIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/workspace/$fileId': typeof WorkspaceFileIdRouteWithChildren
  '/workspace/$fileId/$pageId': typeof WorkspaceFileIdPageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/workspace/$fileId': typeof WorkspaceFileIdRouteWithChildren
  '/workspace/$fileId/$pageId': typeof WorkspaceFileIdPageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/workspace/$fileId': typeof WorkspaceFileIdRouteWithChildren
  '/workspace/$fileId/$pageId': typeof WorkspaceFileIdPageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/workspace/$fileId'
    | '/workspace/$fileId/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/workspace/$fileId' | '/workspace/$fileId/$pageId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/workspace/$fileId'
    | '/workspace/$fileId/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  WorkspaceFileIdRoute: typeof WorkspaceFileIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$fileId': {
      id: '/workspace/$fileId'
      path: '/workspace/$fileId'
      fullPath: '/workspace/$fileId'
      preLoaderRoute: typeof WorkspaceFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$fileId/$pageId': {
      id: '/workspace/$fileId/$pageId'
      path: '/$pageId'
      fullPath: '/workspace/$fileId/$pageId'
      preLoaderRoute: typeof WorkspaceFileIdPageIdRouteImport
      parentRoute: typeof WorkspaceFileIdRoute
    }
  }
}

interface WorkspaceFileIdRouteChildren {
  WorkspaceFileIdPageIdRoute: typeof WorkspaceFileIdPageIdRoute
}

const WorkspaceFileIdRouteChildren: WorkspaceFileIdRouteChildren = {
  WorkspaceFileIdPageIdRoute: WorkspaceFileIdPageIdRoute,
}

const WorkspaceFileIdRouteWithChildren = WorkspaceFileIdRoute._addFileChildren(
  WorkspaceFileIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  WorkspaceFileIdRoute: WorkspaceFileIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
